# Generated by Django 4.1.5 on 2023-04-02 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_usersignup_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 23, 38, 13, 929197)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
