# Generated by Django 4.1.5 on 2023-04-03 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_usersignup_created_alter_usersignup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 9, 31, 34, 280496)),
        ),
    ]
