# Generated by Django 4.1.5 on 2023-04-04 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_milanagent_alter_feedback_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milanagent',
            old_name='comment',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 17, 8, 45, 724388)),
        ),
        migrations.AlterField(
            model_name='milanagent',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 17, 8, 45, 724388)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 17, 8, 45, 724388)),
        ),
    ]
