# Generated by Django 4.1.5 on 2023-04-04 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_blogreply_alter_feedback_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogreply',
            old_name='comment',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='blogreply',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 31, 14, 936129)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 31, 14, 936129)),
        ),
        migrations.AlterField(
            model_name='milanagent',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 31, 14, 936129)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 31, 14, 936129)),
        ),
    ]
