# Generated by Django 4.1.5 on 2023-04-04 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_comment_blogreply_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreply',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 41, 4, 482061)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 41, 4, 482061)),
        ),
        migrations.AlterField(
            model_name='milanagent',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 41, 4, 482061)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 41, 4, 482061)),
        ),
    ]
